//! Proto-generated types (prost)
//!
//! This module contains types auto-generated by prost-build from protobuf definitions.
//! Documentation warnings are suppressed for generated code.

#[allow(missing_docs)]
pub mod eliza {
    #[allow(missing_docs)]
    pub mod v1 {
        include!(concat!(env!("OUT_DIR"), "/eliza.v1.rs"));
    }
}
