/**
 * Config + fetch helpers for the ClawVille Eliza app plugin.
 *
 * ClawVille uses a "runtime-trust" identity model: the plugin passes the
 * Eliza runtime's agentId + character name directly to ClawVille's
 * /api/agent/connect endpoint, and ClawVille derives a stable key of the
 * form `eliza:<elizaAgentId>`. No token exchange, no external identity
 * provider, no OAuth flow. The @clawville/app-clawville plugin itself
 * is the trust boundary — if it's running inside a curated Eliza build,
 * ClawVille accepts its claims at face value.
 *
 * This mirrors the simplicity of app-babylon's auth module but is even
 * simpler because there's no token cache, no X-Api-Key header, and no
 * /auth endpoint to call.
 */

import type { IAgentRuntime } from "@elizaos/core";

const FETCH_TIMEOUT_MS = 8_000;
const DEFAULT_API_BASE = "https://api.clawville.world";
const DEFAULT_VIEWER_URL = "https://clawville.world/game";

// ---------------------------------------------------------------------------
// Runtime ducktyping — same pattern as app-babylon's babylon-auth
// ---------------------------------------------------------------------------

interface RuntimeLike {
  agentId?: string;
  character?: {
    name?: string;
    settings?: { secrets?: Record<string, string> };
    secrets?: Record<string, string>;
  };
  getSetting?: (key: string) => string | null | undefined;
  setSetting?: (key: string, value: string, secret?: boolean) => void;
}

export function asRuntimeLike(value: unknown): RuntimeLike | null {
  return value && typeof value === "object" ? (value as RuntimeLike) : null;
}

/** Read a setting from the runtime, falling back to process.env. */
export function resolveSettingLike(
  runtime: IAgentRuntime | RuntimeLike | null | undefined,
  key: string,
): string | undefined {
  const fromRuntime = runtime?.getSetting?.(key);
  if (typeof fromRuntime === "string" && fromRuntime.trim().length > 0) {
    return fromRuntime.trim();
  }
  const fromEnv = process.env[key];
  if (typeof fromEnv === "string" && fromEnv.trim().length > 0) {
    return fromEnv.trim();
  }
  return undefined;
}

// ---------------------------------------------------------------------------
// Config
// ---------------------------------------------------------------------------

export interface ClawvilleConfig {
  /** Base URL of ClawVille's backend (default: https://api.clawville.world) */
  apiBaseUrl: string;
  /** Base URL of ClawVille's web viewer (default: https://clawville.world/game) */
  viewerUrl: string;
  /** Eliza runtime agent ID — becomes the stable `eliza:<id>` key in ClawVille */
  elizaAgentId: string | undefined;
  /** Eliza character display name — used as the in-game pet name on first spawn */
  elizaCharacterName: string | undefined;
  /** Previously-stored ClawVille sessionId (populated after first connect) */
  storedSessionId: string | undefined;
  /** Previously-stored ClawVille bot UUID (opaque primary key from openclaw_bots) */
  storedUuid: string | undefined;
  /** Previously-stored Solana wallet address (auto-generated by ClawVille) */
  storedWalletAddress: string | undefined;
  runtime: IAgentRuntime | null;
}

export function resolveClawvilleConfig(
  runtime: IAgentRuntime | null,
): ClawvilleConfig {
  const rt = asRuntimeLike(runtime);
  return {
    apiBaseUrl: (
      resolveSettingLike(runtime, "CLAWVILLE_API_URL") ?? DEFAULT_API_BASE
    ).replace(/\/+$/, ""),
    viewerUrl: (
      resolveSettingLike(runtime, "CLAWVILLE_VIEWER_URL") ?? DEFAULT_VIEWER_URL
    ).replace(/\/+$/, ""),
    elizaAgentId: rt?.agentId,
    elizaCharacterName: rt?.character?.name,
    storedSessionId: resolveSettingLike(runtime, "CLAWVILLE_SESSION_ID"),
    storedUuid: resolveSettingLike(runtime, "CLAWVILLE_BOT_UUID"),
    storedWalletAddress: resolveSettingLike(runtime, "CLAWVILLE_WALLET_ADDRESS"),
    runtime,
  };
}

/** Persist connect-time returned values so refreshRunSession can find them later. */
export function stashClawvilleSession(
  runtime: IAgentRuntime | RuntimeLike | null,
  result: { sessionId: string; uuid: string; walletAddress: string | null },
): void {
  if (!runtime?.setSetting) return;
  try {
    runtime.setSetting("CLAWVILLE_SESSION_ID", result.sessionId);
    runtime.setSetting("CLAWVILLE_BOT_UUID", result.uuid);
    if (result.walletAddress) {
      runtime.setSetting("CLAWVILLE_WALLET_ADDRESS", result.walletAddress);
    }
  } catch {
    // Some runtimes don't expose setSetting; fall through silently.
  }
}

// ---------------------------------------------------------------------------
// Fetch helpers
// ---------------------------------------------------------------------------

export interface ClawvilleConnectResponse {
  agentId: string;
  sessionId: string;
  uuid: string;
  isReturning: boolean;
  totalSessions: number;
  knowledge: string[];
  identityType: string;
  autonomyMode: string;
  walletAddress: string | null;
}

/**
 * POST /api/agent/connect — first call of the session. Returns the
 * persistent bot uuid + ephemeral sessionId + auto-generated Solana wallet.
 */
export async function clawvilleConnect(
  config: ClawvilleConfig,
): Promise<ClawvilleConnectResponse> {
  if (!config.elizaAgentId) {
    throw new Error(
      "ClawVille plugin: runtime.agentId is missing — can't derive a eliza identity",
    );
  }

  const url = new URL("/api/agent/connect", config.apiBaseUrl);
  const body = {
    elizaAgentId: config.elizaAgentId,
    elizaCharacterName: config.elizaCharacterName ?? "ElizaAgent",
    // Give the plugin a sensible default avatar; ClawVille auto-picks if omitted.
    name: config.elizaCharacterName ?? "ElizaAgent",
    species: "cat",
    color: 0x66bbff,
    homeX: 640,
    homeY: 400,
    patrolRadius: 100,
    stats: { hp: 100, attack: 10, defense: 10, speed: 10 },
  };

  const response = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
  });

  if (!response.ok) {
    const text = await response.text().catch(() => "");
    throw new Error(
      `ClawVille connect failed (${response.status}): ${text || response.statusText}`,
    );
  }

  return (await response.json()) as ClawvilleConnectResponse;
}

/**
 * GET /api/agent/:sessionId/perception — current world state for an
 * established session. Used by refreshRunSession to keep the Eliza side
 * panel fresh without triggering another /connect round-trip.
 */
export async function clawvillePerception(
  config: ClawvilleConfig,
  sessionId: string,
): Promise<Record<string, unknown> | null> {
  try {
    const url = new URL(
      `/api/agent/${encodeURIComponent(sessionId)}/perception`,
      config.apiBaseUrl,
    );
    const response = await fetch(url, {
      method: "GET",
      headers: { Accept: "application/json" },
      signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
    });
    if (!response.ok) return null;
    return (await response.json()) as Record<string, unknown>;
  } catch {
    return null;
  }
}

/**
 * Generic proxy for any ClawVille sub-route. Used by handleAppRoutes to
 * forward `/api/apps/clawville/:sessionId/move`, `/visit-building`,
 * `/chat`, `/buy`, etc. directly to the backend without any transformation.
 */
export async function proxyClawvilleRequest(
  config: ClawvilleConfig,
  method: string,
  apiPath: string,
  body?: unknown,
): Promise<Response> {
  const url = new URL(apiPath, config.apiBaseUrl);
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
    Accept: "application/json",
  };

  return fetch(url, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
    signal: AbortSignal.timeout(FETCH_TIMEOUT_MS),
  });
}
