/**
 * useWorkflowGenerationState — listens for workflow-generation lifecycle events
 * emitted by AutomationRoomChatPane and returns whether a given workflow is
 * currently being generated by the agent.
 *
 * Event protocol: CustomEvent on `window` with type
 * `milady:automations:workflow-generating` and detail
 * `{ workflowId: string; inProgress: boolean }`.
 *
 * The same pattern is used by `milady:automations:setFilter` in AutomationsView.
 */

import { useEffect, useState } from "react";

export interface WorkflowGeneratingEventDetail {
  workflowId: string;
  inProgress: boolean;
}

/** Emit from the chat pane when generation starts or completes. */
export function emitWorkflowGenerating(
  workflowId: string,
  inProgress: boolean,
): void {
  const detail: WorkflowGeneratingEventDetail = { workflowId, inProgress };
  window.dispatchEvent(
    new CustomEvent<WorkflowGeneratingEventDetail>(
      "milady:automations:workflow-generating",
      { detail },
    ),
  );
}

/**
 * Returns `true` while the agent is generating `workflowId`.
 * Pass `null` to always return `false` (no workflow selected).
 */
export function useWorkflowGenerationState(
  workflowId: string | null | undefined,
): boolean {
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    if (!workflowId) {
      setGenerating(false);
      return;
    }

    const handler = (event: Event) => {
      const detail = (
        event as CustomEvent<WorkflowGeneratingEventDetail>
      ).detail;
      if (detail?.workflowId === workflowId) {
        setGenerating(detail.inProgress);
      }
    };

    window.addEventListener("milady:automations:workflow-generating", handler);
    return () => {
      window.removeEventListener(
        "milady:automations:workflow-generating",
        handler,
      );
    };
  }, [workflowId]);

  // Reset when the workflowId changes (different workflow selected)
  useEffect(() => {
    setGenerating(false);
  }, [workflowId]);

  return generating;
}
