/**
 * Tokagent ↔ Tokagent environment variable aliasing.
 *
 * This is Tokagent-specific and lives in apps/app, NOT in packages/app-core.
 * The alias table is passed to the boot config so that app-core's generic
 * syncBrandEnvToTokagent/syncTokagentEnvToBrand functions can use it.
 */

export const TOKAGENT_ENV_ALIASES = [
  // API & auth
  ["TOKAGENT_API_TOKEN", "TOKAGENT_API_TOKEN"],
  ["TOKAGENT_API_BIND", "TOKAGENT_API_BIND"],
  ["TOKAGENT_PAIRING_DISABLED", "TOKAGENT_PAIRING_DISABLED"],
  ["TOKAGENT_ALLOWED_ORIGINS", "TOKAGENT_ALLOWED_ORIGINS"],
  ["TOKAGENT_ALLOW_NULL_ORIGIN", "TOKAGENT_ALLOW_NULL_ORIGIN"],
  ["TOKAGENT_ALLOW_WS_QUERY_TOKEN", "TOKAGENT_ALLOW_WS_QUERY_TOKEN"],
  ["TOKAGENT_WALLET_EXPORT_TOKEN", "TOKAGENT_WALLET_EXPORT_TOKEN"],
  ["TOKAGENT_TERMINAL_RUN_TOKEN", "TOKAGENT_TERMINAL_RUN_TOKEN"],
  ["TOKAGENT_NAMESPACE", "TOKAGENT_NAMESPACE"],
  ["TOKAGENT_STATE_DIR", "TOKAGENT_STATE_DIR"],
  ["TOKAGENT_CONFIG_PATH", "TOKAGENT_CONFIG_PATH"],
  // Cloud services
  ["TOKAGENT_CLOUD_TTS_DISABLED", "TOKAGENT_CLOUD_TTS_DISABLED"],
  ["TOKAGENT_CLOUD_MEDIA_DISABLED", "TOKAGENT_CLOUD_MEDIA_DISABLED"],
  ["TOKAGENT_CLOUD_EMBEDDINGS_DISABLED", "TOKAGENT_CLOUD_EMBEDDINGS_DISABLED"],
  ["TOKAGENT_CLOUD_RPC_DISABLED", "TOKAGENT_CLOUD_RPC_DISABLED"],
  ["TOKAGENT_DISABLE_LOCAL_EMBEDDINGS", "TOKAGENT_DISABLE_LOCAL_EMBEDDINGS"],
  ["TOKAGENT_DISABLE_EDGE_TTS", "TOKAGENT_DISABLE_EDGE_TTS"],
  // Ports
  ["TOKAGENT_PORT", "TOKAGENT_PORT"],
  ["ELIZA_API_PORT", "ELIZA_API_PORT"],
  ["TOKAGENT_HOME_PORT", "TOKAGENT_HOME_PORT"],
  ["TOKAGENT_GATEWAY_PORT", "TOKAGENT_GATEWAY_PORT"],
  ["TOKAGENT_BRIDGE_PORT", "TOKAGENT_BRIDGE_PORT"],
] as const;
