import {
  type ProviderOption,
  registerProviderOption,
} from "@elizaos/shared/contracts/onboarding";

export const DEFAULT_ONBOARDING_PROVIDER_OPTIONS = [
  {
    id: "elizacloud",
    name: "Eliza Cloud",
    envKey: null,
    pluginName: "@elizaos/plugin-elizacloud",
    keyPrefix: null,
    description: "Managed hosting for Eliza agents and bundled infrastructure.",
    family: "elizacloud",
    authMode: "cloud",
    group: "cloud",
    order: 10,
    recommended: true,
  },
  {
    id: "anthropic-subscription",
    name: "Claude Subscription",
    envKey: null,
    pluginName: "@elizaos/plugin-anthropic",
    keyPrefix: null,
    description:
      "Powers task agents via Claude Code CLI. For the main agent, use Eliza Cloud or a direct API key.",
    family: "anthropic",
    authMode: "subscription",
    group: "subscription",
    order: 20,
    recommended: true,
    labelKey: "providerswitcher.claudeSubscription",
    storedProvider: "anthropic-subscription",
  },
  {
    id: "openai-subscription",
    name: "ChatGPT Subscription",
    envKey: null,
    pluginName: "@elizaos/plugin-openai",
    keyPrefix: null,
    description: "Use your ChatGPT Plus or Pro subscription via OAuth.",
    family: "openai",
    authMode: "subscription",
    group: "subscription",
    order: 30,
    recommended: true,
    labelKey: "providerswitcher.chatgptSubscription",
    storedProvider: "openai-codex",
  },
  {
    id: "anthropic",
    name: "Anthropic",
    envKey: "ANTHROPIC_API_KEY",
    pluginName: "@elizaos/plugin-anthropic",
    keyPrefix: "sk-ant-",
    description: "Claude models via API key.",
    family: "anthropic",
    authMode: "api-key",
    group: "local",
    order: 50,
  },
  {
    id: "openai",
    name: "OpenAI",
    envKey: "OPENAI_API_KEY",
    pluginName: "@elizaos/plugin-openai",
    keyPrefix: "sk-",
    description: "GPT models via API key.",
    family: "openai",
    authMode: "api-key",
    group: "local",
    order: 60,
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    envKey: "OPENROUTER_API_KEY",
    pluginName: "@elizaos/plugin-openrouter",
    keyPrefix: "sk-or-",
    description: "Access multiple models via one API key.",
    family: "openrouter",
    authMode: "api-key",
    group: "local",
    order: 70,
    supportsPrimaryModelOverride: true,
  },
  {
    id: "gemini",
    name: "Gemini",
    envKey: "GOOGLE_GENERATIVE_AI_API_KEY",
    pluginName: "@elizaos/plugin-google-genai",
    keyPrefix: null,
    description: "Google's Gemini models.",
    family: "gemini",
    authMode: "api-key",
    group: "local",
    order: 80,
  },
  {
    id: "grok",
    name: "xAI (Grok)",
    envKey: "XAI_API_KEY",
    pluginName: "@elizaos/plugin-xai",
    keyPrefix: "xai-",
    description: "xAI's Grok models.",
    family: "grok",
    authMode: "api-key",
    group: "local",
    order: 90,
  },
  {
    id: "groq",
    name: "Groq",
    envKey: "GROQ_API_KEY",
    pluginName: "@elizaos/plugin-groq",
    keyPrefix: "gsk_",
    description: "Fast inference.",
    family: "groq",
    authMode: "api-key",
    group: "local",
    order: 100,
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    envKey: "DEEPSEEK_API_KEY",
    pluginName: "@elizaos/plugin-deepseek",
    keyPrefix: "sk-",
    description: "DeepSeek models.",
    family: "deepseek",
    authMode: "api-key",
    group: "local",
    order: 110,
  },
  {
    id: "mistral",
    name: "Mistral",
    envKey: "MISTRAL_API_KEY",
    pluginName: "@elizaos/plugin-mistral",
    keyPrefix: null,
    description: "Mistral AI models.",
    family: "mistral",
    authMode: "api-key",
    group: "local",
    order: 120,
  },
  {
    id: "together",
    name: "Together AI",
    envKey: "TOGETHER_API_KEY",
    pluginName: "@elizaos/plugin-together",
    keyPrefix: null,
    description: "Open-source model hosting.",
    family: "together",
    authMode: "api-key",
    group: "local",
    order: 130,
  },
  {
    id: "ollama",
    name: "Ollama",
    envKey: null,
    pluginName: "@elizaos/plugin-ollama",
    keyPrefix: null,
    description: "Local models, no API key needed.",
    family: "ollama",
    authMode: "local",
    group: "local",
    order: 140,
  },
  {
    id: "zai",
    name: "z.ai",
    envKey: "ZAI_API_KEY",
    pluginName: "@homunculuslabs/plugin-zai",
    keyPrefix: null,
    description: "GLM models via z.ai Coding Plan.",
    family: "zai",
    authMode: "api-key",
    group: "local",
    order: 150,
  },
] as const satisfies ReadonlyArray<ProviderOption>;

let builtInProviderOptionsRegistered = false;

export function registerBuiltInOnboardingProviderOptions(): void {
  if (builtInProviderOptionsRegistered) {
    return;
  }

  for (const option of DEFAULT_ONBOARDING_PROVIDER_OPTIONS) {
    registerProviderOption({ ...option });
  }

  builtInProviderOptionsRegistered = true;
}
