#!/usr/bin/env node
// Dev-time generator: renders "TOKAGENTOS" in ANSI Shadow figlet font and
// writes the lines as a TypeScript string array checked into the repo.
// Run with: bun run scripts/generate-banner.mjs

import figlet from "figlet";
import { writeFileSync } from "node:fs";

const ascii = figlet.textSync("TOKAGENTOS", { font: "ANSI Shadow" });
const lines = ascii.split("\n").filter((l) => l.length > 0);

const content = `// AUTO-GENERATED by scripts/generate-banner.mjs
// Re-run with: bun run scripts/generate-banner.mjs
// Do not edit by hand.

export const BANNER_LINES: readonly string[] = ${JSON.stringify(lines, null, 2)} as const;
`;

const outPath = "packages/tokagentos/src/banner.generated.ts";
writeFileSync(outPath, content);
console.log(`[generate-banner] wrote ${lines.length} lines to ${outPath}`);
