#!/usr/bin/env node
/**
 * Development script that starts:
 * 1. The Eliza dev server (\[(eliza|eliza)(?:-api)?\]|runtime + API on port 31337) with restart support
 * 2. The vite app dev server (port 2138, proxies /api and /ws to 31337)
 *
 * Automatically kills zombie processes on both ports before starting.
 * Waits for the API server to be ready before launching vite so the proxy
 * doesn't flood the terminal with ECONNREFUSED errors.
 *
 * Usage:
 *   node eliza/packages/app-core/scripts/dev-ui.mjs            # starts both API + UI
 *   node eliza/packages/app-core/scripts/dev-ui.mjs --ui-only  # starts only the vite UI (API assumed running)
 */
import { execFileSync, execSync, spawn } from "node:child_process";
import {
  existsSync,
  readFileSync,
  realpathSync,
  writeFileSync,
} from "node:fs";
import { createConnection } from "node:net";
import os from "node:os";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import * as JSON5Module from "json5";
import {
  CAPACITOR_PLUGIN_NAMES,
  NATIVE_PLUGINS_ROOT,
} from "../../../../apps/app/scripts/capacitor-plugin-names.mjs";
import {
  resolveDesktopApiPort,
  resolveDesktopUiPort,
} from "@elizaos/shared/runtime-env";
import { getBunVersionAdvisory } from "./lib/bun-version-guard.mjs";
import { capacitorPluginsBuildNeeded } from "./lib/capacitor-plugin-build-needed.mjs";
import { coerceBoolean } from "./lib/dev-ui-onchain.mjs";
import { buildVisionDepsFailureMessage } from "./lib/dev-ui-vision.mjs";
import { signalSpawnedProcessTree } from "./lib/kill-process-tree.mjs";
import { extendNodePathEnv } from "./lib/node-path-env.mjs";
import { syncElizaEnvAliases } from "./lib/sync-eliza-env-aliases.mjs";

// Load worktree-specific env overrides (ports, state dir) before port resolution.
// Generated by: bash scripts/worktree-env.sh <slot>
const _worktreeEnvPath = path.join(process.cwd(), ".env.worktree");
if (existsSync(_worktreeEnvPath)) {
  const { config: dotenvConfig } = await import("dotenv");
  dotenvConfig({ path: _worktreeEnvPath, override: false });
}

syncElizaEnvAliases();

const API_PORT = resolveDesktopApiPort(process.env);
const JSON5 = JSON5Module.default ?? JSON5Module;

// --app=<name> selects which app to serve (default: "app" → apps/app)
const appArgMatch = process.argv.find((a) => a.startsWith("--app="));
const appName = appArgMatch ? appArgMatch.split("=")[1] : "app";
const APP_UI_PORTS = {
  app: resolveDesktopUiPort(process.env),
  home: Number(process.env.ELIZA_HOME_PORT) || 2142,
};
const UI_PORT = APP_UI_PORTS[appName] ?? 2138;
const appDir = `apps/${appName}`;

function getCliName() {
  const nameArgMatch = process.argv.find((a) => a.startsWith("--name="));
  if (nameArgMatch) return nameArgMatch.split("=")[1];

  try {
    const pkgPath = path.join(process.cwd(), "package.json");
    if (existsSync(pkgPath)) {
      const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
      if (pkg.name) {
        let name = pkg.name;
        if (name.startsWith("@")) name = name.split("/")[1];
        if (
          name === "elizaai" ||
          name === "eliza-ai" ||
          name.includes("eliza")
        )
          return "eliza";
        if (name === "elizaos" || name.includes("eliza")) return "eliza";
        return name;
      }
    }
  } catch (_e) {
    // Ignore parsing errors
  }

  // Fallbacks based on directory structure
  if (
    process.cwd().includes("eliza-workspace") ||
    process.cwd().includes("eliza")
  ) {
    return "eliza";
  }

  return "eliza";
}

const cliName = getCliName();
const logPrefix = `[${cliName}]`;

const bunAdvisory = getBunVersionAdvisory();
if (bunAdvisory) console.warn(`${logPrefix} ${bunAdvisory}`);

const cwd = process.cwd();
const visionDepsScriptPath = fileURLToPath(
  new URL("./ensure-vision-deps.mjs", import.meta.url),
);
const uiOnly = process.argv.includes("--ui-only");
const devLogLevel =
  (process.env.ELIZA_DEV_LOG_LEVEL ?? process.env.LOG_LEVEL ?? "info")
    .trim()
    .toLowerCase() || "info";
const quietApiLogs = process.env.ELIZA_DEV_QUIET_LOGS === "1";
const verboseApiLogs = process.env.ELIZA_DEV_VERBOSE_LOGS !== "0";

function shellQuoteArg(value) {
  return /^[A-Za-z0-9_./:=+-]+$/.test(value) ? value : JSON.stringify(value);
}

const visionDepsRetryCommand = [
  "node",
  path.relative(cwd, visionDepsScriptPath) || visionDepsScriptPath,
  `--name=${cliName}`,
]
  .map(shellQuoteArg)
  .join(" ");
// ---------------------------------------------------------------------------
// ANSI colors — raw escape sequences so we don't need chalk in this .mjs file.
// ---------------------------------------------------------------------------

const supportsColor =
  process.env.FORCE_COLOR !== "0" &&
  process.env.NO_COLOR === undefined &&
  process.stdout.isTTY;

const GREEN = supportsColor ? "\x1b[38;2;0;255;65m" : "";
const ORANGE = supportsColor ? "\x1b[38;2;255;165;0m" : "";
const DIM = supportsColor ? "\x1b[2m" : "";
const RESET = supportsColor ? "\x1b[0m" : "";

function green(text) {
  return `${GREEN}${text}${RESET}`;
}
function orange(text) {
  return `${ORANGE}${text}${RESET}`;
}
function dim(text) {
  return `${DIM}${text}${RESET}`;
}

// ---------------------------------------------------------------------------
// Runtime detection — prefer bun when available, fall back to node/npx.
// ---------------------------------------------------------------------------

function which(cmd) {
  const pathEnv = process.env.PATH ?? "";
  if (!pathEnv) return null;

  const dirs = pathEnv.split(path.delimiter).filter(Boolean);
  const isWindows = process.platform === "win32";
  const pathext = isWindows ? process.env.PATHEXT : "";
  const exts = isWindows
    ? pathext?.length
      ? pathext.split(";").filter(Boolean)
      : [".EXE", ".CMD", ".BAT", ".COM"]
    : [""];

  for (const dir of dirs) {
    const candidates = [cmd];
    if (isWindows) {
      const lowerCmd = cmd.toLowerCase();
      for (const ext of exts) {
        const normalizedExt = ext.startsWith(".") ? ext : `.${ext}`;
        if (!lowerCmd.endsWith(normalizedExt.toLowerCase())) {
          candidates.push(cmd + normalizedExt);
        }
      }
    }
    for (const name of candidates) {
      const candidate = path.join(dir, name);
      if (existsSync(candidate)) return candidate;
    }
  }
  return null;
}

const forceNodeRuntime = process.env.ELIZA_FORCE_NODE === "1";
const hasBun = !forceNodeRuntime && !!which("bun") && !!which("bunx");

if (!hasBun && !which("npx")) {
  console.error(
    'Neither "bun" nor "npx" was found in your PATH. ' +
      "Install Bun or Node.js with npx to run this dev script.",
  );
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Stealth import config
// ---------------------------------------------------------------------------

// coerceBoolean — imported from ./lib/dev-ui-onchain.mjs

function resolveElizaStateDir() {
  const brandedStateDir = process.env.ELIZA_STATE_DIR?.trim();
  if (brandedStateDir) {
    return path.resolve(brandedStateDir);
  }

  const upstreamStateDir = process.env.ELIZA_STATE_DIR?.trim();
  if (upstreamStateDir) {
    return path.resolve(upstreamStateDir);
  }

  const brandedDefault = path.join(os.homedir(), ".eliza");
  if (existsSync(brandedDefault)) {
    return brandedDefault;
  }

  return path.join(os.homedir(), ".eliza");
}

function resolveElizaConfigPath() {
  const explicitConfigPath =
    process.env.ELIZA_CONFIG_PATH?.trim() ||
    process.env.ELIZA_CONFIG_PATH?.trim();
  if (explicitConfigPath) {
    return path.resolve(explicitConfigPath);
  }

  const brandedStateDir = process.env.ELIZA_STATE_DIR?.trim();
  if (brandedStateDir) {
    return path.join(path.resolve(brandedStateDir), "eliza.json");
  }

  const upstreamStateDir = process.env.ELIZA_STATE_DIR?.trim();
  if (upstreamStateDir) {
    return path.join(path.resolve(upstreamStateDir), "eliza.json");
  }

  const brandedDefault = path.join(os.homedir(), ".eliza", "eliza.json");
  if (existsSync(brandedDefault)) {
    return brandedDefault;
  }

  // Keep the legacy Eliza path as a fallback for older local dev setups.
  return path.join(os.homedir(), ".eliza", "eliza.json");
}

function loadElizaConfigForDev() {
  const configPath = resolveElizaConfigPath();
  if (!existsSync(configPath)) return null;
  try {
    const raw = readFileSync(configPath, "utf-8");
    return JSON5.parse(raw);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.warn(
      `${green(logPrefix)} Failed to parse config at ${configPath}: ${msg}`,
    );
    return null;
  }
}

function readPluginStealthFlag(entries, ids) {
  if (!entries || typeof entries !== "object") return null;

  for (const id of ids) {
    const entry = entries[id];
    if (!entry || typeof entry !== "object") continue;

    const config = entry.config;
    if (!config || typeof config !== "object") continue;

    const stealthFlag =
      config.stealthImport ??
      config.enableStealthImport ??
      config.enableStealth;
    const parsed = coerceBoolean(stealthFlag);
    if (parsed !== null) return parsed;
  }

  return null;
}

function resolveStealthImportFlags() {
  let openaiFlag = coerceBoolean(process.env.ELIZA_ENABLE_OPENAI_STEALTH);
  let claudeFlag = coerceBoolean(process.env.ELIZA_ENABLE_CLAUDE_STEALTH);

  const globalFlag = coerceBoolean(process.env.ELIZA_ENABLE_STEALTH_IMPORTS);
  if (globalFlag !== null) {
    openaiFlag = globalFlag;
    claudeFlag = globalFlag;
  }

  const config = loadElizaConfigForDev();
  if (config && typeof config === "object") {
    const feature = config.features?.stealthImports;
    if (typeof feature === "boolean") {
      if (openaiFlag === null) openaiFlag = feature;
      if (claudeFlag === null) claudeFlag = feature;
    } else if (feature && typeof feature === "object") {
      const enabled = coerceBoolean(feature.enabled);
      if (enabled !== null) {
        if (openaiFlag === null) openaiFlag = enabled;
        if (claudeFlag === null) claudeFlag = enabled;
      }

      const openaiFeature =
        coerceBoolean(feature.openai) ?? coerceBoolean(feature.codex);
      const claudeFeature =
        coerceBoolean(feature.claude) ?? coerceBoolean(feature.anthropic);

      if (openaiFeature !== null && openaiFlag === null) {
        openaiFlag = openaiFeature;
      }
      if (claudeFeature !== null && claudeFlag === null) {
        claudeFlag = claudeFeature;
      }
    }

    const pluginEntries = config.plugins?.entries;
    const openaiPluginStealth = readPluginStealthFlag(pluginEntries, [
      "openai",
      "@elizaos/plugin-openai",
      "openai-codex-stealth",
    ]);
    const claudePluginStealth = readPluginStealthFlag(pluginEntries, [
      "anthropic",
      "@elizaos/plugin-anthropic",
      "claude-code-stealth",
    ]);

    if (openaiPluginStealth !== null && openaiFlag === null) {
      openaiFlag = openaiPluginStealth;
    }
    if (claudePluginStealth !== null && claudeFlag === null) {
      claudeFlag = claudePluginStealth;
    }
  }

  // Auto-detect subscription credentials: if the user has logged in via
  // a subscription provider, enable the corresponding stealth interceptor
  // automatically (unless explicitly disabled above).
  const stateDir = resolveElizaStateDir();
  if (openaiFlag === null) {
    const codexAuthPath = path.join(stateDir, "auth", "openai-codex.json");
    if (existsSync(codexAuthPath)) {
      openaiFlag = true;
    }
  }
  if (claudeFlag === null) {
    const anthropicAuthPath = path.join(
      stateDir,
      "auth",
      "anthropic-subscription.json",
    );
    if (existsSync(anthropicAuthPath)) {
      claudeFlag = true;
    }
  }

  return {
    openai: openaiFlag === true,
    claude: claudeFlag === true,
  };
}

// ---------------------------------------------------------------------------
// Output filters for API server logs.
// ---------------------------------------------------------------------------

const SUPPRESS_RE = /^\s*(Info|Warn|Debug|Trace)\s/;
const SUPPRESS_UNSTRUCTURED_RE = /^\[dotenv[@\d]/;
const STARTUP_RE =
  /\[eliza(?:-api)?\]|\[(eliza|eliza)(?:-api)?\]|runtime bootstrap|\[(eliza|eliza)(?:-api)?\]|runtime ready|\[(eliza|eliza)(?:-api)?\]|runtime created|api server ready|plugin.*load|startup.*complete|\d+ms|\[PTYService|\[SwarmCoordinator\]|Triage:/i;

function createErrorFilter(dest) {
  let buf = "";
  return (chunk) => {
    buf += chunk.toString();
    const lines = buf.split("\n");
    buf = lines.pop();
    for (const line of lines) {
      if (
        line.trim() &&
        !SUPPRESS_RE.test(line) &&
        !SUPPRESS_UNSTRUCTURED_RE.test(line)
      ) {
        dest.write(`${line}\n`);
      }
    }
  };
}

function createStartupFilter(dest) {
  let buf = "";
  let lastLine = "";
  let repeatCount = 0;
  return (chunk) => {
    buf += chunk.toString();
    const lines = buf.split("\n");
    buf = lines.pop();
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) continue;
      if (SUPPRESS_UNSTRUCTURED_RE.test(trimmed)) continue;
      if (/embedding dimensions mismatch/i.test(trimmed)) continue;

      if (trimmed === lastLine) {
        repeatCount += 1;
        if (repeatCount > 2) continue;
      } else {
        lastLine = trimmed;
        repeatCount = 0;
      }

      const isWarnOrError = /^\s*(Warn|Error)\s/.test(trimmed);
      const isStartupLine = STARTUP_RE.test(trimmed);
      if (isWarnOrError || isStartupLine) {
        dest.write(`${line}\n`);
      }
    }
  };
}

// ---------------------------------------------------------------------------
// Port cleanup — force-kill zombie processes on our dev ports
// ---------------------------------------------------------------------------

function killPort(port) {
  try {
    if (process.platform === "win32") {
      const out = execSync(
        `netstat -ano | findstr :${port} | findstr LISTENING`,
        { encoding: "utf-8", stdio: ["pipe", "pipe", "ignore"] },
      );
      const pids = new Set(
        out
          .split("\n")
          .map((l) => l.trim().split(/\s+/).pop())
          .filter(Boolean),
      );
      for (const pid of pids) {
        try {
          execSync(`taskkill /F /PID ${pid}`, { stdio: "ignore" });
        } catch {
          /* already dead */
        }
      }
    } else {
      execSync(`lsof -ti :${port} | xargs kill -9 2>/dev/null`, {
        stdio: "ignore",
      });
    }
  } catch {
    // No process found — port is clean
  }
}

// ---------------------------------------------------------------------------
// Wait for a TCP port to accept connections
// ---------------------------------------------------------------------------

function waitForPort(port, { timeout = 120_000, interval = 500 } = {}) {
  return new Promise((resolve, reject) => {
    const deadline = Date.now() + timeout;
    let activeSocket = null;

    function attempt() {
      if (Date.now() > deadline) {
        if (activeSocket) {
          activeSocket.destroy();
          activeSocket = null;
        }
        reject(
          new Error(
            `Timed out waiting for port ${port} after ${timeout / 1000}s`,
          ),
        );
        return;
      }
      activeSocket = createConnection({ port, host: "127.0.0.1" });
      activeSocket.once("connect", () => {
        activeSocket.destroy();
        activeSocket = null;
        resolve();
      });
      activeSocket.once("error", () => {
        activeSocket.destroy();
        activeSocket = null;
        setTimeout(attempt, interval);
      });
    }

    attempt();
  });
}

// ---------------------------------------------------------------------------
// Wait for the agent runtime to be ready (not just the TCP port).
// Polls GET /api/health and resolves when { ready: true }.
// Handles bun --watch restarts gracefully (connection resets → retry).
// ---------------------------------------------------------------------------

async function waitForAgentReady(
  port,
  { timeout = 120_000, interval = 1000 } = {},
) {
  const deadline = Date.now() + timeout;
  const url = `http://127.0.0.1:${port}/api/health`;

  while (Date.now() < deadline) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(3000) });
      if (res.ok) {
        const data = await res.json();
        if (data.ready) return;
      }
    } catch {
      // API not up yet or restarting — keep polling.
    }
    await new Promise((r) => setTimeout(r, interval));
  }

  throw new Error(
    `Agent runtime not ready after ${timeout / 1000}s (port ${port} is up but /api/health never reported ready)`,
  );
}

// ---------------------------------------------------------------------------
// Orphan cleanup (startup only) — never kills arbitrary Bun; PID/name-wide pkill is avoided.
// Only processes whose command line ties them to this repo or Eliza workspace dirs.
// ---------------------------------------------------------------------------

function killOrphanedWorkspaceProcesses() {
  if (process.platform === "win32") return; // spawn-helper is Unix only

  let repoRoot;
  try {
    repoRoot = realpathSync(cwd);
  } catch {
    repoRoot = cwd;
  }

  let psOut;
  try {
    psOut = execSync("ps axo pid=,command=", {
      encoding: "utf8",
      maxBuffer: 10 * 1024 * 1024,
      stdio: ["pipe", "pipe", "ignore"],
    });
  } catch {
    return;
  }

  const workspaceDirRe =
    /\.eliza\/workspaces|\.elizaai\/workspaces|\.eliza\/workspaces|\.elizaai\/workspaces/i;
  const ptyWorkerRe = /pty-worker\.js/i;

  const workspacePids = [];
  const ptyPids = [];

  for (const line of psOut.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    const sp = trimmed.indexOf(" ");
    if (sp < 1) continue;
    const pidStr = trimmed.slice(0, sp).trim();
    const cmd = trimmed.slice(sp + 1);
    const pid = Number.parseInt(pidStr, 10);
    if (!Number.isFinite(pid) || pid <= 0) continue;

    if (workspaceDirRe.test(cmd)) {
      workspacePids.push(pid);
      continue;
    }
    if (ptyWorkerRe.test(cmd) && cmd.includes(repoRoot)) {
      ptyPids.push(pid);
    }
  }

  const killPids = (label, pids) => {
    if (!pids.length) return;
    console.log(`[dev-ui] Killing ${pids.length} orphaned ${label}…`);
    try {
      execSync(`kill -9 ${pids.join(" ")} 2>/dev/null`, { stdio: "ignore" });
    } catch {
      /* ignore */
    }
  };

  killPids("workspace process(es)", workspacePids);
  killPids("repo-scoped pty-worker(s)", ptyPids);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

killOrphanedWorkspaceProcesses();
killPort(UI_PORT);

// Ensure vision dependencies are installed
try {
  execFileSync("node", [visionDepsScriptPath, `--name=${cliName}`], {
    stdio: "inherit",
  });
} catch (error) {
  process.env.ELIZA_VISION_DEPS_STATUS = "degraded";
  console.warn(
    buildVisionDepsFailureMessage(
      error,
      visionDepsRetryCommand,
    ),
  );
}

if (!uiOnly) {
  killPort(API_PORT);
}

let apiProcess = null;
let viteProcess = null;
let shuttingDown = false;

function terminateChild(proc, signal = "SIGTERM") {
  if (!proc) return;
  const sig = signal === "SIGKILL" ? "SIGKILL" : "SIGTERM";
  signalSpawnedProcessTree(proc, sig);
}

function cleanup(exitCode = 0) {
  if (shuttingDown) {
    console.log("\n[eliza] Force exit.");
    process.exit(exitCode === 0 ? 1 : exitCode);
    return;
  }
  shuttingDown = true;

  terminateChild(viteProcess, "SIGTERM");
  terminateChild(apiProcess, "SIGTERM");

  setTimeout(() => {
    terminateChild(viteProcess, "SIGKILL");
    terminateChild(apiProcess, "SIGKILL");
  }, 1500).unref();

  setTimeout(() => {
    process.exit(exitCode);
  }, 1800).unref();
}

process.on("SIGINT", () => cleanup(0));
process.on("SIGTERM", () => cleanup(0));
if (process.platform !== "win32") {
  process.on("SIGHUP", () => cleanup(0));
}

function startVite() {
  const pkgPath = path.join(cwd, appDir, "package.json");
  if (existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"));
      if (pkg.scripts?.["plugin:build"]) {
        const appAbs = path.join(cwd, appDir);
        const pluginsDir = NATIVE_PLUGINS_ROOT;
        const forcePlugins =
          process.env.ELIZA_DEV_PLUGIN_BUILD === "1" ||
          process.env.ELIZA_DEV_PLUGIN_BUILD === "always";
        const skipPlugins =
          process.env.ELIZA_DEV_PLUGIN_BUILD === "0" ||
          process.env.ELIZA_SKIP_PLUGIN_BUILD === "1";
        if (skipPlugins) {
          console.log(
            `  ${green(logPrefix)} ${dim("Skipping Capacitor plugin build (ELIZA_SKIP_PLUGIN_BUILD=1).")}`,
          );
        } else if (
          forcePlugins ||
          capacitorPluginsBuildNeeded(pluginsDir, CAPACITOR_PLUGIN_NAMES)
        ) {
          console.log(
            `  ${green(logPrefix)} Building plugins for ${appDir}...`,
          );
          execSync(hasBun ? "bun run plugin:build" : "npm run plugin:build", {
            cwd: appAbs,
            stdio: "inherit",
            env: process.env,
          });
        } else {
          console.log(
            `  ${green(logPrefix)} ${dim("Capacitor plugins dist up to date (skip rimraf/tsc/rollup). Set ELIZA_DEV_PLUGIN_BUILD=1 to force.")}`,
          );
        }
      }
    } catch (err) {
      console.error(
        `  ${green(logPrefix)} Failed to build plugins for ${appDir}:`,
        err.message,
      );
    }
  }

  const viteCmd = hasBun ? "bunx" : "npx";
  const viteForce =
    process.env.ELIZA_VITE_FORCE === "1" ||
    process.env.ELIZA_VITE_FORCE === "1";
  const viteArgs = viteForce
    ? ["vite", "--force", "--port", String(UI_PORT)]
    : ["vite", "--port", String(UI_PORT)];
  if (viteForce) {
    console.log(
      `  ${green(logPrefix)} ${dim("Vite --force (ELIZA_VITE_FORCE=1): re-optimizing deps.")}`,
    );
  }
  viteProcess = spawn(viteCmd, viteArgs, {
    cwd: path.join(cwd, appDir),
    env: {
      ...process.env,
      NODE_ENV: "development",
      ELIZA_NAMESPACE: cliName,
      ELIZA_UI_PORT: String(UI_PORT),
      ELIZA_API_PORT: String(API_PORT),
      ELIZA_PORT: String(UI_PORT),
      ELIZA_HOME_API_PORT: String(API_PORT),
    },
    stdio: ["inherit", "pipe", "pipe"],
  });

  viteProcess.on("error", (err) => {
    console.error(`  ${green(logPrefix)} Failed to start vite: ${err.message}`);
    cleanup(1);
  });

  viteProcess.stdout.on("data", (data) => {
    const text = data.toString();
    if (text.includes("ready")) {
      console.log(
        `\n  ${green(logPrefix)} ${orange(`http://localhost:${UI_PORT}/`)}\n`,
      );
    }
  });

  viteProcess.stderr.on("data", (data) => {
    process.stderr.write(data);
  });

  viteProcess.on("exit", (code) => {
    if (shuttingDown) return;
    if (code !== 0) {
      console.error(
        `${green(logPrefix)} vite exited with code ${code} — API server continues without UI`,
      );
    }
  });
}

if (uiOnly) {
  startVite();
} else {
  console.log(`${orange(`\n${cliName} dev mode`)}\n`);
  console.log(`  ${green(logPrefix)} ${green("Starting dev server...")}\n`);
  console.log(
    `  ${green(logPrefix)} ${dim(
      `API log level=${devLogLevel}${
        quietApiLogs
          ? " (errors only)"
          : verboseApiLogs
            ? " (verbose)"
            : " (startup + warnings/errors)"
      }`,
    )}`,
  );

  // Security default: stealth shims are disabled unless explicitly enabled
  // via env vars or plugin config in eliza.json.
  const stealth = resolveStealthImportFlags();
  const nodeStealthImports = [];
  if (stealth.openai) nodeStealthImports.push("./openai-codex-stealth.mjs");
  if (stealth.claude) nodeStealthImports.push("./claude-code-stealth.mjs");

  const resolvedStealthImports = nodeStealthImports.filter((filePath) =>
    existsSync(path.join(cwd, filePath)),
  );
  if (resolvedStealthImports.length > 0) {
    console.log(
      `  ${green(logPrefix)} ${dim(`Stealth imports enabled: ${resolvedStealthImports.join(", ")}`)}`,
    );
  }

  const apiCmd = hasBun
    ? [
        "bun",
        "--no-install",
        ...resolvedStealthImports.flatMap((filePath) => [
          "--preload",
          filePath,
        ]),
        "--watch",
        "eliza/packages/app-core/src/runtime/dev-server.ts",
      ]
    : [
        "node",
        ...resolvedStealthImports.flatMap((filePath) => ["--import", filePath]),
        "--import",
        "tsx",
        "--watch",
        "eliza/packages/app-core/src/runtime/dev-server.ts",
      ];
  apiProcess = spawn(apiCmd[0], apiCmd.slice(1), {
    cwd,
    env: extendNodePathEnv(
      {
        ...process.env,
        NODE_ENV: "development",
        ELIZA_NAMESPACE: cliName,
        ELIZA_API_PORT: String(API_PORT),
        ELIZA_UI_PORT: String(UI_PORT),
        ELIZA_PORT: String(UI_PORT),
        ELIZA_HEADLESS: "1",
        ELIZA_DEV_AUTH_BYPASS: "1",
        LOG_LEVEL: devLogLevel,
      },
      cwd,
    ),
    stdio: ["inherit", "pipe", "pipe"],
  });

  apiProcess.on("error", (err) => {
    console.error(
      `  ${green(logPrefix)} Failed to start API server: ${err.message}`,
    );
    cleanup(1);
  });

  if (quietApiLogs) {
    apiProcess.stderr.on("data", createErrorFilter(process.stderr));
    apiProcess.stdout.on("data", () => {});
  } else if (verboseApiLogs) {
    apiProcess.stderr.on("data", (data) => {
      process.stderr.write(data);
    });
    apiProcess.stdout.on("data", (data) => {
      process.stdout.write(data);
    });
  } else {
    apiProcess.stderr.on("data", createStartupFilter(process.stderr));
    apiProcess.stdout.on("data", createStartupFilter(process.stdout));
  }

  apiProcess.on("exit", (code) => {
    if (shuttingDown) return;
    if (code !== 0) {
      console.error(`\n  ${green(logPrefix)} Server exited with code ${code}`);
      cleanup(code ?? 1);
    }
  });

  const startTime = Date.now();
  let phase = "port";
  const dots = setInterval(() => {
    const elapsed = ((Date.now() - startTime) / 1000).toFixed(0);
    const msg =
      phase === "port"
        ? "Waiting for API server..."
        : "Waiting for agent to be ready...";
    process.stdout.write(
      `\r  ${green(logPrefix)} ${green(`${msg} ${dim(`${elapsed}s`)}`)}`,
    );
  }, 1000);

  waitForPort(API_PORT)
    .then(() => {
      const portElapsed = ((Date.now() - startTime) / 1000).toFixed(1);
      process.stdout.write(
        `\r  ${green(logPrefix)} ${green(`API port open`)} ${dim(`(${portElapsed}s)`)}          \n`,
      );
      phase = "agent";
      return waitForAgentReady(API_PORT);
    })
    .then(() => {
      clearInterval(dots);
      const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
      console.log(
        `\r  ${green(logPrefix)} ${green(`Agent ready`)} ${dim(`(${elapsed}s)`)}          `,
      );
      startVite();
    })
    .catch((err) => {
      clearInterval(dots);
      console.error(`\n  ${green(logPrefix)} ${err.message}`);
      cleanup(1);
    });
}
