#!/usr/bin/env bash
# Generate .env.worktree for isolated multi-instance dev.
#
# Usage:
#   bash scripts/worktree-env.sh [slot]
#
# slot: integer offset (default 1). Slot 0 = default ports, slot 1 = +100,
#       slot 2 = +200, etc. Each slot gets its own state directory too.
#
# The generated .env.worktree is auto-loaded by dev-ui.mjs, dev-platform.mjs,
# and run-node.mjs before port resolution, so `bun run dev` Just Works.

set -euo pipefail

SLOT=${1:-1}
OFFSET=$((SLOT * 100))

API_PORT=$((31337 + OFFSET))
UI_PORT=$((2138 + OFFSET))
HOME_PORT=$((2142 + OFFSET))
GATEWAY_PORT=$((18789 + OFFSET))
STATE_DIR="~/.milady-wt-${SLOT}"

cat > .env.worktree <<EOF
# Worktree isolation — slot ${SLOT}
# Generated by: bash scripts/worktree-env.sh ${SLOT}
# Regenerate with a different slot number to change ports.

MILADY_API_PORT=${API_PORT}
MILADY_PORT=${UI_PORT}
MILADY_HOME_PORT=${HOME_PORT}
MILADY_GATEWAY_PORT=${GATEWAY_PORT}
MILADY_STATE_DIR=${STATE_DIR}
EOF

echo "Wrote .env.worktree (slot ${SLOT})"
echo "  API:     ${API_PORT}"
echo "  UI:      ${UI_PORT}"
echo "  Home:    ${HOME_PORT}"
echo "  Gateway: ${GATEWAY_PORT}"
echo "  State:   ${STATE_DIR}"
