/**
 * Persists agent settings to the on-disk `.env` file so they survive
 * a server restart.
 *
 * Background: `runtime.setSetting(key, value)` only writes to in-memory
 * runtime state. After the next process restart, the value is gone — so
 * a deployed vault address would be forgotten and the vault-context
 * provider would (incorrectly) say "no vault deployed" on the next turn.
 *
 * Strategy: best-effort dual-write — set the in-memory setting first,
 * then mirror the same key to the on-disk `.env`. Disk-write failures
 * are logged but never thrown; the in-memory setting still works for
 * the current session.
 *
 * The on-disk path resolves to:
 *   1. `process.env.DOTENV_PATH` if set (operator override)
 *   2. `<process.cwd()>/.env` otherwise
 *
 * No `dotenv` dependency: we use plain `fs` so this stays usable from
 * any runtime context (CLI scaffolding, plugin actions, tests).
 */
import * as fs from 'node:fs';
import * as path from 'node:path';

/**
 * Structural duck-type for any runtime-like object that may expose a
 * `setSetting`. We deliberately do NOT require `getSetting` here — this
 * helper writes only — and we widen the value parameter to `unknown` so
 * we accept both the read-only `AgentRuntimeLike` and the wider eliza
 * `IAgentRuntime` (whose `getSetting` returns `string | number | boolean
 * | null`). Avoiding a hard import on `@elizaos/core` keeps this package
 * usable from CLI scaffolding contexts that don't pull in the runtime.
 */
export interface RuntimeSettingWriter {
  setSetting?: (key: string, value: string) => unknown | Promise<unknown>;
}

function resolveDotenvPath(): string {
  if (typeof process !== 'undefined' && process.env?.DOTENV_PATH) {
    return path.resolve(process.env.DOTENV_PATH);
  }
  return path.resolve(process.cwd(), '.env');
}

/**
 * Upserts a single `KEY=value` line in a `.env`-formatted string.
 *
 * - If `key` already exists (line starts with `KEY=`, ignoring leading
 *   whitespace), its value is replaced in-place — every other line is
 *   preserved verbatim (comments, blank lines, ordering).
 * - If `key` is absent, a new line is appended at the end.
 * - Trailing newline is normalized.
 *
 * Exported for tests; not part of the public package surface.
 */
export function upsertEnvLine(content: string, key: string, value: string): string {
  const newLine = `${key}=${value}`;
  const lines = content.split(/\r?\n/);
  // Drop a single trailing empty token created by a final '\n' so we don't
  // append two blank lines on every write.
  const hadTrailingNewline = lines.length > 0 && lines[lines.length - 1] === '';
  if (hadTrailingNewline) lines.pop();

  let replaced = false;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    // Skip comments and blank lines for the key match. Match `^\s*KEY=`
    // (no support for `export KEY=` — keep the format simple).
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=/);
    if (m && m[1] === key) {
      lines[i] = newLine;
      replaced = true;
      break;
    }
  }
  if (!replaced) {
    lines.push(newLine);
  }
  return `${lines.join('\n')}\n`;
}

const DEFAULT_HEADER =
  '# Generated by tokagent — vault address persistence.\n' +
  '# This file is read by your agent runtime and should be kept in sync\n' +
  '# with TOKAGENT_VAULT_ADDRESS_<chainId> entries.\n';

function writeKeyToDotenv(filePath: string, key: string, value: string): void {
  let next: string;
  if (!fs.existsSync(filePath)) {
    next = `${DEFAULT_HEADER}${key}=${value}\n`;
  } else {
    const current = fs.readFileSync(filePath, 'utf8');
    next = upsertEnvLine(current, key, value);
  }
  fs.writeFileSync(filePath, next, 'utf8');
}

/**
 * Persist a vault address for a given chainId to BOTH:
 *   1. the in-memory runtime setting (`TOKAGENT_VAULT_ADDRESS_<chainId>`)
 *   2. the on-disk `.env` (so it survives a process restart)
 *
 * Disk-write errors are logged with `console.warn` and swallowed — the
 * in-memory setting is enough for the current session, and we should
 * never undo a successful on-chain deploy by throwing here.
 */
export async function persistVaultAddress(
  runtime: RuntimeSettingWriter,
  chainId: number,
  vault: string,
): Promise<void> {
  const key = `TOKAGENT_VAULT_ADDRESS_${chainId}`;

  // 1. In-memory (best-effort). Don't throw if `setSetting` is missing
  //    or rejects — the runtime contract varies across versions.
  if (typeof runtime.setSetting === 'function') {
    try {
      await runtime.setSetting(key, vault);
    } catch (err) {
      console.warn(
        `[tokagent persist] failed to set runtime setting ${key}: ${
          err instanceof Error ? err.message : String(err)
        }`,
      );
    }
  }

  // 2. On-disk .env mirror. Never throw — degrade to in-memory only.
  try {
    const filePath = resolveDotenvPath();
    writeKeyToDotenv(filePath, key, vault);
  } catch (err) {
    console.warn(`[tokagent persist] failed to write .env: ${err}`);
  }
}
