/**
 * Eliza ↔ Eliza environment variable aliasing.
 *
 * This is Eliza-specific and lives in apps/app, NOT in packages/app-core.
 * The alias table is passed to the boot config so that app-core's generic
 * syncBrandEnvToEliza/syncElizaEnvToBrand functions can use it.
 */

export const ELIZA_ENV_ALIASES = [
  // API & auth
  ["ELIZA_API_TOKEN", "ELIZA_API_TOKEN"],
  ["ELIZA_API_BIND", "ELIZA_API_BIND"],
  ["ELIZA_PAIRING_DISABLED", "ELIZA_PAIRING_DISABLED"],
  ["ELIZA_ALLOWED_ORIGINS", "ELIZA_ALLOWED_ORIGINS"],
  ["ELIZA_ALLOW_NULL_ORIGIN", "ELIZA_ALLOW_NULL_ORIGIN"],
  ["ELIZA_ALLOW_WS_QUERY_TOKEN", "ELIZA_ALLOW_WS_QUERY_TOKEN"],
  ["ELIZA_WALLET_EXPORT_TOKEN", "ELIZA_WALLET_EXPORT_TOKEN"],
  ["ELIZA_TERMINAL_RUN_TOKEN", "ELIZA_TERMINAL_RUN_TOKEN"],
  ["ELIZA_NAMESPACE", "ELIZA_NAMESPACE"],
  ["ELIZA_STATE_DIR", "ELIZA_STATE_DIR"],
  ["ELIZA_CONFIG_PATH", "ELIZA_CONFIG_PATH"],
  // Cloud services
  ["ELIZA_CLOUD_TTS_DISABLED", "ELIZA_CLOUD_TTS_DISABLED"],
  ["ELIZA_CLOUD_MEDIA_DISABLED", "ELIZA_CLOUD_MEDIA_DISABLED"],
  ["ELIZA_CLOUD_EMBEDDINGS_DISABLED", "ELIZA_CLOUD_EMBEDDINGS_DISABLED"],
  ["ELIZA_CLOUD_RPC_DISABLED", "ELIZA_CLOUD_RPC_DISABLED"],
  ["ELIZA_DISABLE_LOCAL_EMBEDDINGS", "ELIZA_DISABLE_LOCAL_EMBEDDINGS"],
  ["ELIZA_DISABLE_EDGE_TTS", "ELIZA_DISABLE_EDGE_TTS"],
  // Ports
  ["ELIZA_PORT", "ELIZA_PORT"],
  ["ELIZA_API_PORT", "ELIZA_API_PORT"],
  ["ELIZA_HOME_PORT", "ELIZA_HOME_PORT"],
  ["ELIZA_GATEWAY_PORT", "ELIZA_GATEWAY_PORT"],
  ["ELIZA_BRIDGE_PORT", "ELIZA_BRIDGE_PORT"],
] as const;
